title: AI Conference Deadlines # (Maintained by @abhshkdz)
# email: abhshkdz@vt.edu
description: Self-updating countdown timers to keep track of a bunch of CV/NLP/ML/AI conference deadlines, because things can quickly get out of hand.

baseurl: ""
twitter_username: abhshkdz
github_username: abhshkdz

markdown: kramdown
ga_id: UA-36274081-2
