title: Academic Deadlines (Maintained by @abhshkdz)
email: abhshkdz@vt.edu
description: Timer to keep track of a bunch of CV/ML/AI conference deadlines, because things can quickly get out of hand.

baseurl: /~abhshkdz
url: https://computing.ece.vt.edu
twitter_username: abhshkdz
github_username: abhshkdz

markdown: kramdown
ga_id: UA-36274081-2
